// <auto-generated />
using System;
using DotNetCoreBlog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreBlog.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20181101145623_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCoreBlog.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .IsUnicode(true);

                    b.Property<DateTimeOffset>("PubDate");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true);

                    b.Property<string>("Tags")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Posts");

                    b.HasData(
                        new { Id = 1, Body = @"# Creavit ante inde vestras inde

## Ulixes nec violas tepido adveniens et petitur

Lorem markdownum lapis temptamina prima, qua ululare umbras territaque videt. Et
illum, credi saepe ille rursus accipite Solis, clara ferro haud, simulacraque
gentis? Omni removi crematisregia suis ante Cytherea rapitur latera. Manus audet
mora et vidit litora fit in considere usus arma *sedet auxilio*, ingemuit natus
protexi Tartareas.

## Carent nec stratis lina genis terram in

Unus alios sinistra reddidit in sicco. Huic permulcens vident, non est thalamo
prima cum obstitit et harenam tectus signa. Monstri globos sertaque caderet
Alcmene quippe spicula; amisit non vita possit atras domo est, culta. Plaustrum
vultumque gentemque tecto Hectoris labor, latens ne quam edidit Procne
contemptaque inde fragiles?

## Manum instantem flammis addere

Retia magna da guttur firma: quem: et cum est altaria negaretur est tuta
perdidimus! Hostem populos **me discussa** Alcmene habet, cum semper est latera
notavi matres, rursus.

Aera praemia; nec ecce foci, celsum tacito terra; pallor motaque minimos nollet.
Huc alios priori indignave maenala precor serpentem quoque mandata adpulit,
paravi te nubibus concutio. Et currus saepe tenebris ignes tegens hunc, *petiit
coniuge* opacas. Auro non solent.

## Feretrumque talia potentia datum in quid inpubesque

Stratis nec res placuisse, maritum, nusquam; aura *sole silicem simul*. Sed
secus spesque, placet latebras parvas sollicitis graniferumque manibus?

> Mutantur propiora mea Pleiadum candida Achilles etiam conducat colubrasque
> altis meritumque suarum labant. Quam opposuitque tibi spargimur gramina haec.
> Inde adhuc et latices recentes tenebrisque virgo sidoniae.

Caeli obside. Qui mecum ac aera est **lupum quondam silvas** centumque distabat:
sceptra inde petendo. Rogaberis inania, sed ipsa. Nam bella collumque nectare
iussit, nec fallaces, induit adnuit. Nutricisque meum homine *conatibus*
murmure, a!", PubDate = new DateTimeOffset(new DateTime(2018, 11, 1, 14, 56, 23, 296, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), Summary = "Lorem markdownum lapis temptamina prima, qua ululare umbras territaque videt. Etillum, credi saepe ille rursus accipite Solis, clara ferro haud, simulacraque gentis ? Omni removi crematisregia suis ante Cytherea rapitur latera.Manus audet mora et vidit litora fit in considere usus arma * sedet auxilio *, ingemuit natus protexi Tartareas.", Tags = "first,demo", Title = "First post!", UrlSlug = "first-post" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
